image: python:3.5

before_script:
  - apt-get -qq update && apt-get -qq install -y python-pip
  - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - sphinx-build -nWT -b dummy source build
